---
title: "Examen final Modules 4 et 5"
author: "Alexandre Godmer"
subtitle: "DUBii 2021"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: resources/biblio.bib 
csl: resources/biomed-central.csl
output:
    html_document:
      css: [css/style.css, 'https://use.fontawesome.com/releases/v5.0.9/css/all.css']
      self_contained: true
      number_sections: false
      code_folding: "hide"
      toc: true
      toc_depth: 3
      toc_float: true
      includes:
        after_body: resources/footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=FALSE, echo =TRUE, cache = FALSE, message = FALSE, warning = FALSE, cache.lazy = FALSE,
                      fig.height = 3.5, fig.width = 10.5)
```

# Consignes {-}

Complétez ce document en remplissant les chunks vides pour écrire le code qui vous a permis de répondre à la question. Les réponses attendant un résultat chiffré ou une explication devront être insérés entre le balises html `code`. Par exemple pour répondre à la question suivante :

    La bioinfo c'est : <code>MERVEILLEUX</code>.
    
N'hésitez pas à commenter votre code, enrichier le rapport en y insérant des résultats ou des graphiques/images pour expliquer votre démarche. N'oubliez pas les **bonnes pratiques** pour une recherche **reproductible** !
Nous souhaitons à minima que l'analyse soit reproductible sur le cluster de l'IFB.

# Introduction {-}

Vous allez travailler sur des données de reséquençage d'un génome bactérien : _Bacillus subtilis_. Les données sont issues de cet article :

* [Complete Genome Sequences of 13 Bacillus subtilis Soil Isolates for Studying Secondary Metabolite Diversity](https://mra.asm.org/content/9/2/e01406-19)

# Analyses

## Organisation de votre espace de travail

```{bash}
## Repertoire de travail
pwd
#/shared/projects/dubii2021/agodmer

## Enregistrement de l'arborescence dans le fichier Evaluation_M4_M5/supplemental_data/Organisation_espace_de_travail.txt
tree > supplemental_data/Organisation_espace_de_travail.txt

## Commande tree
tree

#[agodmer@clust-slurm-client Evaluation_M4_M5]$ tree
#.
#|-- DATA_analysis
#|   |-- CLEANING
#|   |-- FASTQ
#|   |-- MAPPING
#|   |-- QC
#|   `-- REFERENCE_GENOME
#|-- EvaluationM4M5-main-results
#|   |-- Evaluation.Rmd
#|   |-- Evaluation.html
#|   |-- EvaluationM4M5.Rproj
#|   |-- README.md
#|   |-- css
#|   |   `-- style.css
#|   |-- images
#|   |   |-- inrae.png
#|   |   `-- migale-orange.png
#|   `-- resources
#|       |-- biblio.bib
#|       |-- biomed-central.csl
#|       `-- footer.html
#|-- LICENSE
#|-- README.md
#`-- supplemental_data
#    |-- Organisation_espace_de_travail.txt
#    `-- README_supp_data.md

 
## Il n'y a pas de modification à faire pour l'instant
```

## Téléchargement des données brutes

Récupérez les fichiers FASTQ issus du run **SRR10390685** grâce à l'outil <strong class="tool">sra-tools</strong> @sratoolkit

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/EvaluationM4M5-main-results

## Charger le module SRA tools avec la dernière version 
module avail sra-tools
module load sra-tools/2.10.3

## Utilisation de la commande fasterq-dump pour télécharger les fichiers 

## Visualisation de la version
fasterq-dump --version
#"fasterq-dump" version 2.10.3

## Ecriture de la version de fasterq-dump sur le fichier Version_tools.txt dans supplemental_data
fasterq-dump --version > ../supplemental_data/Version_tools.txt

## Changement du répertoire de travail
cd ..

## Reservation des ressources pour le cluster
salloc --cpus-per-task=6 --mem=5G

## Télécharger les fichiers FASTQ
srun fasterq-dump --split-files -p SRR10390685 --outdir DATA_analysis/FASTQ/

## Lister les fichiers et regarder leur taille
ls -sh DATA_analysis/FASTQ/
#total 5.0G
#2.5G SRR10390685_1.fastq  2.5G SRR10390685_2.fastq

## Compression des fichier FASTQ avec mode verbeux acitvé
srun gzip --verbose DATA_analysis/FASTQ/*.fastq

# Liste des fichier et taille
ls -sh DATA_analysis/FASTQ/
#total 1.3G
#617M SRR10390685_1.fastq.gz  627M SRR10390685_2.fastq.gz

## La compression a bien fonctionnée !

```

Combien de reads sont présents dans les fichiers R1 et R2 ?

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis

## Chargement du module seqkit
module avail seqkit
module load seqkit/0.14.0
## Ecriture de la version de seqkit sur le fichier Version_tools.txt dans supplemental_data
seqkit version >> ../supplemental_data/Version_tools.txt

## Comptage des read présents et écriture des statistiques dans le fichier Raw_stats_fastq.txt dans Results/supplemental_data
srun seqkit stats --threads 1 FASTQ/*.fastq.gz > ../supplemental_data/Raw_stats_fastq.txt

## Visualisation des résultats
cat ../supplemental_data/Raw_stats_fastq.txt

#file                          format  type   num_seqs        sum_len  min_len  avg_len  max_len
#FASTQ/SRR10390685_1.fastq.gz  FASTQ   DNA   7,066,055  1,056,334,498       35    149.5      151
#FASTQ/SRR10390685_2.fastq.gz  FASTQ   DNA   7,066,055  1,062,807,718      130    150.4      151

```

Les fichiers FASTQ contiennent <code>7,066,055</code> reads.

Téléchargez le génome de référence de la souche ASM904v1 de _Bacillus subtilis_ disponible à [cette adresse](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.fna.gz)

```{bash}
## Repertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis

## Téléchargement du génome de référence
srun wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.fna.gz

## Visualisation du fichier
ls -sh
#total 68K
#68K GCF_000009045.1_ASM904v1_genomic.fna.gz

```

Quelle est la taille de ce génome ?

```{bash}

## Taille du génome de référence
## Enregistrement du résultats dans Stats_genome_ref.txt
zcat GCF_000009045.1_ASM904v1_genomic.fna.gz | grep -v "^>" | tr --delete "\n" | wc -c > ../../supplemental_data/Stats_genome_ref.txt

## Visualisation du fichier
cat ../../supplemental_data/Stats_genome_ref.txt
#4215606

```

La taille de ce génome est de <code>4215606</code> paires de bases.

Téléchargez l'annotation de la souche ASM904v1 de _Bacillus subtilis_ disponible à [cette adresse](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.gff.gz)

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis/REFERENCE_GENOME

## Téléchargement de l'annotation du génome
srun wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/GCF_000009045.1_ASM904v1_genomic.gff.gz

## Visualisation des fichiers
ls -sh

#total 1.3M
#1.2M GCF_000009045.1_ASM904v1_genomic.fna.gz   69K GCF_000009045.1_ASM904v1_genomic.gff.gz

```

Combien de gènes sont connus pour ce génome ?

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis/REFERENCE_GENOME

## Enregistrement du résultats dans Stats_genome_ref_nb_genes.txt
less GCF_000009045.1_ASM904v1_genomic.gff.gz | awk '($3 == "gene")' | wc -l > ../../supplemental_data/Stats_genome_ref_nb_genes.txt

## Visualisation du fichier
cat ../../supplemental_data/Stats_genome_ref_nb_genes.txt
#4448
```

<code>4448</code> gènes sont recensés dans le fichier d'annotation.

## Contrôle qualité

Lancez l'outil <strong class="tool">fastqc</strong> @fastqc dédié à l'analyse de la qualité des bases issues d'un séquençage haut-débit

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis

module avail fastqc
module load fasqc/0.11.9
## Ecriture de la version de fastqc sur le fichier Version_tools.txt dans supplemental_data
fastqc --version >> ../supplemental_data/Version_tools.txt

## Réservation des resources pour le cluster
salloc --cpus-per-task=8 --mem=10G

## Lancement de la commande fastqc
srun fastqc FASTQ/SRR10390685_1.fastq.gz -o QC/ -t 8
srun fastqc FASTQ/SRR10390685_2.fastq.gz -o QC/ -t 8

## Copie des rapport htlm vers supplemental data
cp QC/*html ../supplemental_data/

```

La qualité des bases vous paraît-elle satisfaisante ? Pourquoi ?

- [X] Oui
- [ ] Non


car <code> la qualité (estimée par le score Phred) de chaque base pour tous les reads de votre jeu de données est en moyenne et en médiane supérieure à 30 (cette valeur correspond à la probabilité de 1 pour 1000 q'une base ait été identifiée incorectement) </code> comme le montre <code>le graphique **Per base sequence quality** qui représente représente la qualité (score Phred, en ordonnée) de chaque base (en abscisse) pour tous les reads de votre jeu de données ; Le code couleur vous indique les scores de très bonne qualité en vert pour la majorité de nos reads. La qualité des reads sur la plupart des plates-formes se dégradera au fur et à mesure de la progression du séquençage, il est donc courant de voir la qualité des reads entrer dans la zone orange vers la fin d'une lecture. On peut observer un warning sur **Per base sequence content** qui trace le pourcentage de chacun des quatre nucléotides à chaque position sur toutes les lectures dans le fichier de séquence d'entrée. Cependant La proportion de chacune des quatre bases reste relativement constante sur la longueur de la lecture avec AT et GC et les lignes du graphiques sont parallèles les unes aux autres. La sur-représentation des bases AT est concordante avec le poucentage de GC de l'espèce étudiée (*Bacillus subtilis*) qui n'est pas égal à 50% mais à 43% sur le génome de référence  *Bacillus subtilis subsp. subtilis str. 168* [NCBI](https://www.ncbi.nlm.nih.gov/genome/?term=Bacillus%20subtilis%5BOrganism%5D&cmd=DetailsSearch). </code>

- Lien vers le [rapport MulitQC SRR10390685_1](https://agodmer.github.io/Evaluation_M4_M5/supplemental_data/SRR10390685_1_fastqc.html)
- Lien vers le [rapport MulitQC SRR10390685_2](https://agodmer.github.io/Evaluation_M4_M5/supplemental_data/SRR10390685_2_fastqc.html)

Est-ce que les reads déposés ont subi une étape de nettoyage avant d'être déposés ? Pourquoi ?

- [X] Oui
- [ ] Non

car <code> Les reads n'ont pas la même longueur, de plus, on remarque que les adaptateurs ont été enlevés sur le graphique **Adapter Content**. </code>

Quelle est la profondeur de séquençage (calculée par rapport à la taille du génome de référence) ?

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5

## Formule :  N*L/G ; avec N = Nombre de lectures, L = Longueur des lectures et G = Taille du génome

## taille du génome de référence (G)
zcat DATA_analysis/REFERENCE_GENOME/GCF_000009045.1_ASM904v1_genomic.fna.gz |grep -v "^>"|wc -c
#4268302

## Récupération des données : Nombre de lecture (N), Longueur des lectures (L)
 cat supplemental_data/Raw_stats_fastq.txt
 
#file                          format  type   num_seqs        sum_len  min_len  avg_len  max_len
#FASTQ/SRR10390685_1.fastq.gz  FASTQ   DNA   7,066,055  1,056,334,498       35    149.5      151
#FASTQ/SRR10390685_2.fastq.gz  FASTQ   DNA   7,066,055  1,062,807,718      130    150.4      151

## profondeur = N*L/G 
echo "(7066055*149.5 + 7066055*150.4)/4268302" | bc
#496

## Ecriture de la version de fastqc sur le fichier profondeur_seq_vs_genomeref.txt dans supplemental_data
echo "(7066055*149.5 + 7066055*150.4)/4268302" | bc > supplemental_data/profondeur_seq_vs_genomeref.txt

```

La profondeur de séquençage est de : <code>496</code> X.

## Nettoyage des reads

Vous voulez maintenant nettoyer un peu vos lectures. Choisissez les paramètres de <strong class="tool">fastp</strong> @fastp qui vous semblent adéquats et justifiez-les.

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis

## Chargement du module fastp
module avail fastp
module load fastp/0.20.0
## Ecriture de la version de fastp sur le fichier Version_tools.txt dans supplemental_data
fastp --version >> ../supplemental_data/Version_tools.txt # A revoir ne fonctionne pas !

## Ressources sur le cluster
salloc --cpus-per-task=8 --mem=5G

## Lancement de la commande fastp avec les paramètres choisis
srun fastp --in1 FASTQ/SRR10390685_1.fastq.gz --in2 FASTQ/SRR10390685_2.fastq.gz --out1 CLEANING/SRR10390685_1_clean.fastq.gz --
out2 CLEANING/SRR10390685_2_clean.fastq.gz --html ./fastp.html --cut_mean_quality 30 --cut_window_size 8 --length_required 100 --cut_tail --json CLEANING/fastp.json

## Statistiques sur les read apres nettoyage avec fastp et écriture dans le fichier After_cleaning_stats_fastq.txt dans supplemental_data
srun seqkit stats --threads 1 CLEANING/*.fastq.gz > ../supplemental_data/After_cleaning_stats_fastq.txt

## Nombres de reads conservés
cat ../supplemental_data/After_cleaning_stats_fastq.txt

#file                                   format  type   num_seqs      sum_len  min_len  avg_len  max_len
#CLEANING/SRR10390685_1_clean.fastq.gz  FASTQ   DNA   6,777,048  996,891,051      100    147.1      151
#CLEANING/SRR10390685_2_clean.fastq.gz  FASTQ   DNA   6,777,048  990,442,597      100    146.1      151

## Calcul du nombre de reads conservés
echo "(7066055-6777048)/7006055" | bc

#b = (7066055-6777048)/7006055
#b*100 
#4.13%
```

Les paramètres suivants ont été choisis : 


|Parametre | Valeur | Explication |
|----------|--------|-------------|
|cut_mean_quality| 30 | Nettoyage des reads en fin de séquençage avec une qualité un peu plus basse|
|cut_window_size|8||
|length_required|100||
|cut_tail |||
Ces paramètres ont permis de conserver <code>6,777,048</code> reads pairés, soit une perte de <code>4,1</code>% des reads bruts.

## Alignement des reads sur le génome de référence

Maintenant, vous allez aligner ces reads nettoyés sur le génome de référence à l'aide de <strong class="tool">bwa</strong> @bwa et <strong class="tool">samtools</strong> @samtools.

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis

## Chargement du module bwa
module avail bwa
module load bwa/0.7.17

## Il n'y a pas de commande "Version", écriture de la version du module dans le fichier Version_tool.txt avec l'éditeur de texte nano

## Création d'un FASTA index sur le génome de référence
srun bwa index REFERENCE_GENOME/GCF_000009045.1_ASM904v1_genomic.fna.gz

## Ressources du cluster
salloc --cpus-per-task=32 --mem=5G

## Mapping en utilisant la commande bwa mem
srun bwa mem REFERENCE_GENOME/GCF_000009045.1_ASM904v1_genomic.fna.gz CLEANING/SRR10390685_1_clean.fastq.gz CLEANING/SRR10390685_2_clean.fastq.gz -t 8 > MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sam

## Chargement du module samtools
module avail samtools
module load samtools/1.10

## Ecriture de la version de samtools sur le fichier Version_tools.txt dans supplemental_dat
samtools --version >> ../supplemental_data/Version_tools.txt

## Ressources du cluster
salloc --cpus-per-task=8 --mem=5G

## Conversion du fichier SAM en BAM
samtools view MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sam -b > MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.bam

## Trier le fichier BAM avec la commande samtools sort
srun samtools sort MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sam -o MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sort.bam

## Indexage du fichier BAM trié
srun samtools index MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sort.bam

## Supression des fichiers inutiles
rm -f MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sam SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.bam
```

Combien de reads ne sont pas mappés ?

```{bash}
## Répertoire de travail
pwd
#/shared/projects/dubii2021/agodmer/Evaluation_M4_M5/DATA_analysis

## Statistiques de MAPPING
srun samtools idxstats MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sort.bam > ../supplemental_data/SRR10390685.sort.bam.idxstats
srun samtools flagstat MAPPING/SRR10390685_on_GCF_000009045.1_ASM904v1_genomic_reference.1.sort.bam > ../supplemental_data/SRR10390685.sort.bam.flagstat

## Calcul du nombre de reads non mappés

cat ../supplemental_data/SRR10390685.sort.bam.flagstat
#13571369 + 0 in total (QC-passed reads + QC-failed reads)
#0 + 0 secondary
#17273 + 0 supplementary
#0 + 0 duplicates
#12826829 + 0 mapped (94.51% : N/A)
#13554096 + 0 paired in sequencing
#6777048 + 0 read1
#6777048 + 0 read2
#12746420 + 0 properly paired (94.04% : N/A)
#12769290 + 0 with itself and mate mapped
#40266 + 0 singletons (0.30% : N/A)
#0 + 0 with mate mapped to a different chr
#0 + 0 with mate mapped to a different chr (mapQ>=5)

## Nombre de reads non mappés (total des reads : "mapped" + "singletons" + unmapped) ; unmapped = "total" - "mapped" - "singletons"
echo "13571369-12826829-40266" | bc
#704274
```


<code>704274</code> reads ne sont pas mappés.

## Croisement de données

Calculez le nombre de reads qui chevauchent avec au moins 50% de leur longueur le gène _trmNF_ grâce à l'outil <strong class="tool">bedtools</strong> @bedtools:

```{bash}

```

<code> </code> reads chevauchent le gène d'intérêt.


## Visualisation

Utilisez <strong class="tool">IGV</strong> @igv sous [sa version en ligne](https://igv.org/app/) pour visualiser les alignements sur le gène. Faites une capture d'écran du gène entier.

# References